export const carBrands = [
  { id: 1, name: "Acura" },
  { id: 2, name: "Alfa Romeo" },
  { id: 3, name: "Audi" },
  { id: 4, name: "BMW" },
  { id: 5, name: "Bentley" },
  { id: 6, name: "Buick" },
  { id: 7, name: "Cadillac" },
  { id: 8, name: "Chevrolet" },
  { id: 9, name: "Chrysler" },
  { id: 10, name: "Dodge" },
  { id: 11, name: "Ferrari" },
  { id: 12, name: "Fiat" },
  { id: 13, name: "Ford" },
  { id: 14, name: "GMC" },
  { id: 15, name: "Genesis" },
  { id: 16, name: "Honda" },
  { id: 17, name: "Hyundai" },
  { id: 18, name: "Infiniti" },
  { id: 19, name: "Jaguar" },
  { id: 20, name: "Jeep" },
  { id: 21, name: "Kia" },
  { id: 22, name: "Lamborghini" },
  { id: 23, name: "Land Rover" },
  { id: 24, name: "Lexus" },
  { id: 25, name: "Lincoln" },
  { id: 26, name: "Lotus" },
  { id: 27, name: "Maserati" },
  { id: 28, name: "Mazda" },
  { id: 29, name: "McLaren" },
  { id: 30, name: "Mercedes-Benz" },
  { id: 31, name: "Mini" },
  { id: 32, name: "Mitsubishi" },
  { id: 33, name: "Nissan" },
  { id: 34, name: "Porsche" },
  { id: 35, name: "Ram" },
  { id: 36, name: "Rolls-Royce" },
  { id: 37, name: "Subaru" },
  { id: 38, name: "Tesla" },
  { id: 39, name: "Toyota" },
  { id: 40, name: "Volkswagen" },
  { id: 41, name: "Volvo" },
  { id: 42, name: "Other" },
];

export const indianStatesAndCities = [
  {
    id: 1,
    state: "Kerala",
    cities: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam"],
  },
  {
    id: 2,
    state: "Tamilnadu",
    cities: ["Chennai", "Coimbatore", "Madurai", "Salem", "Tiruchirappalli"],
  },
  {
    id: 3,
    state: "Karnataka",
    cities: ["Bengaluru", "Mysuru", "Hubli", "Mangaluru", "Belagavi"],
  },
];
